### ISSUE TITLE
Module2 week 1 day 2

### ISSUE THREAD

**Issue by souad988** [zmekonnen251/Awsome-books#2]

**Comment by mnekx** [comment]
-Local storage could have been tested before usage because some browsers might have been disabled the local storage and it could break your site.
-UL could carry better semantic meaning for containing the books
-For performance purposes, the removal approach could be improved. Don't you think?
Otherwise, the class design is lit 🔥 good job.

**Comment by souad988** [comment]
you did a good job implementing the requirement i like the fact that you are adding only the new book to the DOM this is good for the performance, but i have one thing to mention, the bookCollection class it should contain only book functionalities add to list and remove from list but not the html elements this way your code can be reusable .

**Comment by Tufahel** [comment]
Awesome!! You have done an excellent job in this project especially implementing javascript.
- It is not a must but you can consider using a section tag to wrap up h1, div, and form in index.html.
- Also, you can consider the suggestions of previous commentators @mnekx  and @souad988 as, those suggestions will help regarding your code usability and performance.

**Comment by zmekonnen251** [comment]
Thanks, guys for your constructive feedback 👍 . I accept all of your feedback and work on them.

**Comment by ahangarha** [comment]
> you did a good job implementing the requirement i like the fact that you are adding only the new book to the DOM this is good for the performance, but i have one thing to mention, the bookCollection class it should contain only book functionalities add to list and remove from list but not the html elements this way your code can be reusable .

Great comment. Thank you for this. I am thinking if we can pass template to the class. Don't know the best practice. If you know, please share.

**Comment by souad988** [comment]
> > you did a good job implementing the requirement i like the fact that you are adding only the new book to the DOM this is good for the performance, but i have one thing to mention, the bookCollection class it should contain only book functionalities add to list and remove from list but not the html elements this way your code can be reusable .
> 
> Great comment. Thank you for this. I am thinking if we can pass template to the class. Don't know the best practice. If you know, please share.

may be you can create a new class that takes a liste as argument and create elements with ids for liste items then add styling for those items in css file, the idea is the maximum generalized the class is the best is will be
